"""bookingfile model

Revision ID: 10e2ca340f17
Revises: 899ed3bc4a4e
Create Date: 2026-01-17 19:17:28.290430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlalchemy_utc
import sqlmodel.sql.sqltypes
from sqlmodel import Text

import fastapi_storages.integrations.sqlalchemy
from fastapi_storages import FileSystemStorage

# revision identifiers, used by Alembic.
revision: str = '10e2ca340f17'
down_revision: Union[str, Sequence[str], None] = '899ed3bc4a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_files',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('booking_id', sa.Integer(), nullable=False),
                    # sa.Column('file', fastapi_storages.integrations.sqlalchemy.FileType(), nullable=False),
                    sa.Column('file', fastapi_storages.integrations.sqlalchemy.FileType(
                        storage=FileSystemStorage(path="uploads/bookings")), nullable=False),
                    # sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
                    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='fk_booking_files_booking_id'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # op.create_unique_constraint('uq_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('uq_email', 'users', type_='unique')
    op.drop_table('booking_files')
    # ### end Alembic commands ###
