"""add attendance_status field

Revision ID: 899ed3bc4a4e
Revises: f4b157537e75
Create Date: 2026-01-17 11:56:01.840160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlalchemy_utc
import sqlmodel.sql.sqltypes
from sqlmodel import Text

# revision identifiers, used by Alembic.
revision: str = '899ed3bc4a4e'
down_revision: Union[str, Sequence[str], None] = 'f4b157537e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('attendance_status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    with op.batch_alter_table('bookings') as batch_op:
        batch_op.create_unique_constraint('uq_email', ['email'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), nullable=False))
    with op.batch_alter_table('bookings') as batch_op:
        batch_op.drop_constraint('uq_email', type_='unique')
    op.drop_column('users', 'hashed_password')
    op.drop_column('bookings', 'attendance_status')
    # ### end Alembic commands ###
