"""Add Account status

Revision ID: ae4e356150ba
Revises: 10e2ca340f17
Create Date: 2026-01-18 18:47:27.699521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlalchemy_utc
import sqlmodel.sql.sqltypes
from sqlmodel import Text

from appserver.apps.account.enums import AccountStatus

# revision identifiers, used by Alembic.
revision: str = 'ae4e356150ba'
down_revision: Union[str, Sequence[str], None] = '10e2ca340f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'status',
            sa.String(),
            nullable=False,
            server_default=AccountStatus.ACTIVE.value,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
